spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:resume}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin123}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

      dialect: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true

security:
  jwt:
    secret: ${JWT_SECRET:ChangeThisToALongRandomSecretAtLeast32Chars}
    expiration: ${JWT_EXP_SECONDS:3600}

logging:
  level:
    org.hibernate.SQL: info
    org.springframework.security: info