spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:resume}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin123}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

      dialect: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true


logging:
  level:
    org.hibernate.SQL: info
    org.springframework.security: info